vich_uploader:
    db_driver: orm

    mappings:
        services_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        technologies_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        works_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        catalog_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        categories_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        promo_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    